version: "3.8"

networks:
    app-network:
        driver: bridge

services:
    backend:
        build: ./job-rocket-backend
        container_name: rocket-backend

    frontend:
        build: ./job-rocket-frontend
        container_name: rocket-frontend
        ports:
            - "80:80"
        depends_on:
            - backend
