# 1. Build 단계: Node.js를 사용하여 React 애플리케이션 빌드
FROM node:16 as build

# 작업 디렉토리 설정
WORKDIR /app

# package.json과 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 애플리케이션 소스 코드 복사
COPY . .

# React 애플리케이션 빌드
RUN npm run build

# 2. Serve 단계: Nginx를 사용하여 정적 파일 서빙
FROM nginx:1.23

# Nginx 설정 파일 덮어쓰기 (선택 사항)
# Nginx 설정 파일은 프로젝트 디렉토리의 `nginx.conf` 파일을 기준으로 복사
COPY nginx.conf /etc/nginx/conf.d/default.conf

# React 빌드 결과물 복사
COPY --from=build /app/dist /usr/share/nginx/html

# Nginx 기본 포트 노출
EXPOSE 80

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]